# Programming Assignment 0: Crash Course Intro to Numpy
developped by Georgian Tutuianu. Adapted by Huaizu Jiang.

## Overview
<font size="4">This notebook introduces some basic familiarity with python and numpy by coding with integer filled arrays.</font>
 
<font size="4">Hopefully this is useful!</font>

## Tips and Tricks
<font size="4">These may be useful until you are more comfortable with numpy:</font>

* <font size="4">Use intermediate variables when manually broadcasting numpy dimensions through reshaping or repeating elements. 
     <p>&emsp;This helps to visualize what ararys look like. <p></font>
* <font size="4">Continually check the shape of your output. 
     <p>&emsp;print(array.shape) is your friend! <p></font>
* <font size="4">When trying to broadcast for example multiplying two arrays of shape:<br />
<p>&emsp;(8, 3, 5) * (3, 5) will yield a shape mismatch error<p><br />
    <p>&emsp;You can usually get what you want if you fill missing dimensions by 1<p><br />
    <p>&emsp;(8, 3, 5) * (1, 3, 5) &emsp;&emsp;The 1 makes numpy automatically broadcast <p>
    <p>&emsp;Sometimes this isn't what we actually want so be careful. <p>
</font>
* <font size="4">Add your own unit tests. </font>

## Setup

In [ ]:
%matplotlib inline
%matplotlib notebook
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('..')
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# !pip install colour
# !pip install iteration_utilities
import time
import datetime

# Programming assignment starts here (48 points in total)

## Part 1: Array Indexing
<font size="4">For the given integer 2D array get the first, middle and last rows and elements.</font><br />
<font size="4">Assume only odd sized arrays as input.</font><br />
<font size="4">Assume array rows are all the same length.</font><br />
<font size="4">Assume array will not be empty.</font>

<font size="4">
<pre>
Example:
        [[ 0  1  2  3  4]
         [ 5  6  7  8  9]
         [10 11 12 13 14]
         [15 16 17 18 19]
         [20 21 22 23 24]]
    
Answer:
        first row:  [ 0  1  2  3  4]
        middle row: [10 11 12 13 14]
        last row:   [20 21 22 23 24]
        first element =    0
        middle element = 12
        last element =   24

<font size="4" color="red">**task 1.1: Compute using naive python implementation. (2 points).**</font><br><br>

In [ ]:
def get_rows_and_elements_py(array_2d):
    """
    Returns the first, middle & last rows & elements of a 2D matrix using simple python.
    See above examples for more information.

    Args:
        array_2d: A 2D python array of integers of size n by m.
        
    Returns:
        result: Tuple containing the first, middle & last rows & elements 
            of the given array.
    """
    row_first = None
    row_mid = None
    row_end = None
    element_first = None
    element_mid = None
    element_end = None
    
    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    result = (row_first, row_mid, row_end, element_first, element_mid, element_end)
    
    return result

In [ ]:
# let's check your naive python implementation
from pa0_unit_tests.test_part1 import test_get_rows_and_elements_1
from pa0_unit_tests.test_part1 import test_get_rows_and_elements_2
from pa0_unit_tests.test_part1 import test_get_rows_and_elements_3
from pa0_unit_tests.test_part1 import test_get_rows_and_elements_4

# Test 1
result_test_1 = get_rows_and_elements_py(np.array([[0, 1, 2]]))
test_get_rows_and_elements_1(result_test_1)

# Test 2
result_test_2 = get_rows_and_elements_py(np.arange(9).reshape(3, 3))
test_get_rows_and_elements_2(result_test_2)

# Test 3
result_test_3 = get_rows_and_elements_py(np.arange(25).reshape(5, 5))
test_get_rows_and_elements_3(result_test_3)

# Test 4
result_test_4 = get_rows_and_elements_py(
    np.array([[72], [64], [36], [8], [78], [29], [49]]))
test_get_rows_and_elements_4(result_test_4)

<font size="4" color="red">**task 1.2: Compute using numpy implementation. (2 points).**</font><br><br>
<font size="4">May be very similar to python version (except for indexing).</font>

In [ ]:
def get_rows_and_elements_np(array_2d: np.ndarray):
    """
    Returns the first, middle & last rows & elements of a 2D matrix using numpy.
    See above examples for more information.

    Args:
        array_2d: A numpy array of shape (N, M).
        
    Returns:
        result: Tuple containing the first, middle & last rows & elements 
            of the given array.
    """
    row_first = None
    row_mid = None
    row_end = None
    element_first = None
    element_mid = None
    element_end = None
    
    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    result = (row_first, row_mid, row_end, element_first, element_mid, element_end)
    
    return result

In [ ]:
# let's check your numpy implementation

# Test 1
result_test_1 = get_rows_and_elements_np(np.array([[0, 1, 2]]))
test_get_rows_and_elements_1(result_test_1)

# Test 2
result_test_2 = get_rows_and_elements_np(np.arange(9).reshape(3, 3))
test_get_rows_and_elements_2(result_test_2)

# Test 3
result_test_3 = get_rows_and_elements_np(np.arange(25).reshape(5, 5))
test_get_rows_and_elements_3(result_test_3)

# Test 4
result_test_4 = get_rows_and_elements_np(
    np.array([[72], [64], [36], [8], [78], [29], [49]]))
test_get_rows_and_elements_4(result_test_4)

## Part 2: More Array Indexing
<font size="4">For the given integer 2D array get:<br />
    a. median value of each row and column. <br />
    b. index of the median value of each row and column.<br />
    c. average value of each row and column.</font>
<pre>
Example:
        [[ 0  1  2  3  4]
         [ 5  6  7  8  9]
         [10 11 12 13 14]
         [15 16 17 18 19]
         [20 21 22 23 24]]
    
Answer:
        median row values       : [ 2.  7. 12. 17. 22.] (middle column)
        median col values       : [10. 11. 12. 13. 14.] (middle row)
        median row value indices: [ 2  7 12 17 22]
        median col value indices: [10 11 12 13 14]
        average row value       : [ 2.  7. 12. 17. 22.]
        average col value       : [10. 11. 12. 13. 14.]

In [ ]:
def print_medians(array_2d: np.ndarray, func):
    """
    Helper function to visualize the output of get_medians_np or get_medians_py

    Args:
        array_2d: A numpy array of shape (N, M).
        func : placeholder that takes either the get_medians_np or get_medians_py function

    Returns: Nothing.
    """
    (median_rows, median_cols,
     median_row_values_from_idx, median_col_values_from_idx, 
     mean_rows, mean_cols) = func(array_2d)
    
    message = (
        f"median row values       : {median_rows}\n"
        f"median col values       : {median_cols}\n"
        f"median row value indices: {median_row_values_from_idx}\n"
        f"median col value indices: {median_col_values_from_idx}\n"
        f"average row value       : {mean_rows}\n"
        f"average col value       : {mean_cols}\n"
        )
    print(message)

<font size="4" color="red">**task 2.1: Compute using naive python implementation. (6 points).**</font><br><br>

In [ ]:
def get_medians_py(array_2d):
    """
    Returns the:
        a. median value of each row and column,
        b. index of the median value of each row and column,
        c. average value of each row and column,

    of a 2D matrix using numpy. See above examples for more information.

    Args:
        array_2d: A python list with N rows and M columns per row.

    Returns:
        result: Tuple containing the median values and indices and the average values
            over the rows and columns of the given array.
    """
    median_rows = None 
    median_cols = None 
    median_row_values_from_idx = None 
    median_col_values_from_idx = None 
    mean_rows = None 
    mean_cols = None 
    
    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    result = (median_rows, 
              median_cols,
              median_row_values_from_idx, 
              median_col_values_from_idx,
              mean_rows, 
              mean_cols)

    return result

In [ ]:
# let's check your naive python implementation
from pa0_unit_tests.test_part2 import test_get_medians_1
from pa0_unit_tests.test_part2 import test_get_medians_2
from pa0_unit_tests.test_part2 import test_get_medians_3
from pa0_unit_tests.test_part2 import test_get_medians_4

# Test 1
result_test_1 = get_medians_py(np.array([[0, 1, 2]]))
test_get_medians_1(result_test_1)

# Test 2
result_test_2 = get_medians_py(np.arange(9).reshape(3, 3))
test_get_medians_2(result_test_2)

# Test 3
result_test_3 = get_medians_py(np.arange(25).reshape(5, 5))
test_get_medians_3(result_test_3)

# Test 4
result_test_4 = get_medians_py(
    np.array([[72], [64], [36], [8], [78], [29], [49]]))
test_get_medians_4(result_test_4)

<font size="4" color="red">**task 2.2: Compute using numpy implementation. (6 points).**</font><br><br>

In [ ]:
def get_medians_np(array_2d: np.ndarray):
    """
    Returns the:
        a. median value of each row and column,
        b. index of the median value of each row and column,
        c. average value of each row and column,

    of a 2D matrix using numpy. See above examples for more information.

    Args:
        array_2d: A numpy array of shape (N, M).

    Returns:
        result: Tuple containing the median values and indices and the average values
            over the rows and columns of the given array.
    """
    median_rows = None 
    median_cols = None 
    median_row_values_from_idx = None 
    median_col_values_from_idx = None 
    mean_rows = None 
    mean_cols = None 
    
    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    result = (median_rows, median_cols,
              median_row_values_from_idx, median_col_values_from_idx,
              mean_rows, mean_cols)

    return result

In [ ]:
# let's check your numpy implementation

# Test 1
result_test_1 = get_medians_np(np.array([[0, 1, 2]]))
test_get_medians_1(result_test_1)

# Test 2
result_test_2 = get_medians_np(np.arange(9).reshape(3, 3))
test_get_medians_2(result_test_2)

# Test 3
result_test_3 = get_medians_np(np.arange(25).reshape(5, 5))
test_get_medians_3(result_test_3)

# Test 4
result_test_4 = get_medians_np(
    np.array([[72], [64], [36], [8], [78], [29], [49]]))
test_get_medians_4(result_test_4)

## Part 3: Array Multiplication
<font size="4">For the given integer 2D array multiply each row of the given masking array<br />
    by the given 2D array and then take the sum such that the shape of the given 2D array is preserved.<br /></font>
<pre>
Example:
given array:
            [[0 1 2]
             [3 4 5]
             [6 7 8]]

masking array:
            [[0 1 1]
             [1 1 0]]
        
multiply each mask by the given array
            [[[0 0 0]
              [3 4 5]
              [6 7 8]]

             [[0 1 2]
              [3 4 5]
              [0 0 0]]]

take the total sum to get

Answer:
            [[ 0  1  2]
             [ 6  8 10]
             [ 6  7  8]]

<font size="4" color="red">**task 3.1: Compute using naive python implementation. (10 points).**</font><br><br>

In [ ]:
def mask_multiply_py(array_2d, mask_2d):
    """
    Multiplies each row of the given masking array by the given 2D array
    and returns the sum such that the shape of the given 2D array is preserved.

    See above example for more information.

    Args:
        array_2d: A python array where N is the number of rows and M columns.
        mask_2d: A python array where B is the number of masks of N columns.

    Returns:
        final_sum: A numpy array representing the summed masked row of the given array.
            shape (N, M)
    """
    final_sum = None 
    
    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    
    return final_sum

In [ ]:
# let's check your naive python implementation
from pa0_unit_tests.test_part3 import test_mask_multiply_1
from pa0_unit_tests.test_part3 import test_mask_multiply_2
from pa0_unit_tests.test_part3 import test_mask_multiply_3
from pa0_unit_tests.test_part3 import test_mask_multiply_4
from pa0_unit_tests.test_part3 import test_mask_multiply_5
from pa0_unit_tests.test_part3 import test_mask_multiply_6
from pa0_unit_tests.test_part3 import test_mask_multiply_7
from pa0_unit_tests.test_part3 import test_mask_multiply_8

# Test 1
test_mask_multiply_1(mask_multiply_py)

# Test 2
test_mask_multiply_2(mask_multiply_py)

# Test 3
test_mask_multiply_3(mask_multiply_py)

# Test 4
test_mask_multiply_4(mask_multiply_py)

# Test 5
test_mask_multiply_5(mask_multiply_py)

# Test 6
test_mask_multiply_6(mask_multiply_py)

# Test 7
test_mask_multiply_7(mask_multiply_py)

# Test 8
test_mask_multiply_8(mask_multiply_py)

<font size="4" color="red">**task 3.2:  Compute using numpy implementation. (10 points).**</font><br><br>

In [ ]:
def mask_multiply_np(array_2d: np.ndarray, mask_2d: np.ndarray):
    """
    Multiplies each row of the given masking array by the given 2D array
    and returns the sum such that the shape of the given 2D array is preserved.

    See above example for more information.

    Args:
        array_2d: A numpy array where N is the number of rows and M columns.
            shape (N, M)
        mask_2d: A numpy array where B is the number of masks of N columns.
            shape (B, N)

    Returns:
        final_sum: A numpy array representing the summed masked row of the given array.
            shape (N, M)
    """
    final_sum = None 
    
    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    
    return final_sum

In [ ]:
# let's check your numpy implementation

# Test 1
test_mask_multiply_1(mask_multiply_np)

# Test 2
test_mask_multiply_2(mask_multiply_np)

# Test 3
test_mask_multiply_3(mask_multiply_np)

# Test 4
test_mask_multiply_4(mask_multiply_np)

# Test 5
test_mask_multiply_5(mask_multiply_np)

# Test 6
test_mask_multiply_6(mask_multiply_np)

# Test 7
test_mask_multiply_7(mask_multiply_np)

# Test 8
test_mask_multiply_8(mask_multiply_np)

## Part 4: Some Useful Functions
* <font size="4">np.arange                      </font>
* <font size="4">np.where                       </font>
* <font size="4">np.repeat                      </font>
* <font size="4">np.tile                        </font>

## Part 4.1: np.arange
<font size="4">Given the number of rows and columns return an array filled with consecutive integers <br />
    starting from 0 and ending at N * M - 1 where N is the number of rows and M is the number of columns.<br />
</font>
<pre>
Example:
given:
            N: 3
            M: 3

Answer:
            [[0 1 2]
             [3 4 5]
             [6 7 8]]

## Note:
<font size="4">np.arange is extremely useful and much more powerful than this example.<br />
See the documentation here: <br />
https://numpy.org/doc/stable/reference/generated/numpy.arange.html
</font>

<font size="4" color="red">**task 4.1.1: Compute using naive python implementation. (1 points).**</font><br><br>

In [ ]:
def arange_py(N, M):
    """
    Fills an array with consecutive integers starting from 0 and ending at N * M - 1

    See above example for more information.

    Args:
        N: integer representing the number of rows in the 2D array.
        M: integer representing the number of columns in the 2D array.

    Returns:
        aranged: A numpy array representing the consecutively filled array.
            shape (N, M)
    """
    aranged = None 

    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    
    return aranged

In [ ]:
# let's check your naive python implementation
from pa0_unit_tests.test_part4 import test_arange_1
from pa0_unit_tests.test_part4 import test_arange_2

# Test 1
result_1 = arange_py(10, 1)
test_arange_1(result_1)

# Test 2
result_2 = arange_py(1, 10)
test_arange_2(result_2)

<font size="4" color="red">**task 4.1.2: Compute using numpy implementation. (1 points).**</font><br><br>

In [ ]:
def arange_np(N, M):
    """
    Fills an array with consecutive integers starting from 0 and ending at N * M - 1

    See above example for more information.

    Args:
        N: integer representing the number of rows in the 2D array.
        M: integer representing the number of columns in the 2D array.

    Returns:
        aranged: A numpy array representing the consecutively filled array.
            shape (N, M)
    """
    aranged = None 

    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    
    return aranged

In [ ]:
# let's check your numpy implementation

# Test 1
result_1 = arange_np(10, 1)
test_arange_1(result_1)

# Test 2
result_2 = arange_np(1, 10)
test_arange_2(result_2)

## Part 4.2: np.where
<font size="4">Given an integer 2D array and a set of target values in an array.<br />
    Return the row and column indices of the target values from the 2D source array and <br />
    using these indices return the values of the source array.
</font>
<pre>
Example:
source array:
        [[ 0  1  2  3]
         [ 4  5  6  7]
         [ 8  9 10 11]
         [12 13 14 15]]

target array:
        [1 6 8 14]
Answer:
    row indices               : [0 1 2 3]
    col indices               : [1 2 0 2]
    target values from indices: [1 6 8 14]

## Note:
<font size="4">np.where is extremely useful and much more powerful than this example.<br />
See the documentation here: <br />
https://numpy.org/doc/stable/reference/generated/numpy.where.html
</font>

<font size="4">You may be getting the following warning:<br />
    <code>DeprecationWarning: element-wise comparison failed; this will raise an error in the future.</code><br />
    <br />
    This is because the np.where requires the shapes to match. <br />
    In the future comparisons between arrays will be preferred using np.array_equal(array1, array2) instead of 
    array1 == array2. The former explicitly checks the shape of both arrays which the == method does not.
</font>

<font size="4" color="red">**task 4.2.1: Compute using naive python implementation. (5 points).**</font><br><br>

In [ ]:
def where_py(array_2d, targets):
    """
    Finds the index of the values of the targets in the given 2D array.

    See above example for more information.

    Args:
        array_2d: A python integer array where N is the number of rows and M columns.
            shape (N, M)
        targets: A python integer array of target values whose index to find.
            shape unenforced

    Returns:
        result: Tuple containing the row and column indices of the targets 
            as well as the values at these indices.
    
    Hint:
        The deepflatten function from the iteration_utilities library may be useful here.
    """
    row_idx = None
    col_idx = None
    values_by_idx = None

    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    
    result = [row_idx, col_idx, values_by_idx]
    
    return result

<font size="4" color="red">**task 4.2.2: Compute using numpy implementation. (1 points).**</font><br><br>

In [ ]:
def where_np(array_2d: np.ndarray, targets: np.ndarray):
    """
    Finds the index of the values of the targets in the given 2D array.

    See above example for more information.

    Args:
        array_2d: A numpy integer array where N is the number of rows and M columns.
            shape (N, M)
        targets: A numpy integer array of target values whose index to find.
            shape unenforced

    Returns:
        result: Tuple containing the row and column indices of the targets 
            as well as the values at these indices.
    """
    row_idx = None
    col_idx = None
    values_by_idx = None
    
    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
        
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    
    result = [row_idx, col_idx, values_by_idx]
    return result

In [ ]:
array_4x4 = np.arange(16).reshape(4, 4)
print("Array:")
print(array_4x4)
print("\n")
    
# case 1 first diagonal
print("Case 1 first diagonal")
target = np.array([0, 5, 10, 15])
print(f"Searching for target: {target}")
print("\n")
indices = np.where(array_4x4 == target)
print("indices")
print(indices)
print("\n")

if len(indices[0]):
    ys = indices[0]
    xs = indices[1]
    values_by_idx = array_4x4[(ys, xs)]
    print("values_by_idx")
    print(values_by_idx)
else:
    print("No indices were found.")
    print("values_by_idx = []")

In [ ]:
array_4x4 = np.arange(16).reshape(4, 4)
print("Array:")
print(array_4x4)
print("\n")

# case 2 second diagonal
print("Case 2 second diagonal")
target = np.array([3, 6, 9, 12])
print(f"Searching for target: {target}")
print("\n")
# target = np.array([12, 9, 6, 3])

indices = np.where(array_4x4 == target)
print("indices")
print(indices)
print("\n")

if len(indices[0]):
    ys = indices[0]
    xs = indices[1]
    values_by_idx = array_4x4[(ys, xs)]
    print("values_by_idx")
    print(values_by_idx)
else:
    print("No indices were found.")
    print("values_by_idx = []")

<font size="4">What's going on here?<br /> 
    All of the target value are present in given array! <br />
    See the next example for the answer. <br />
</font>

In [ ]:
array_4x4 = np.arange(16).reshape(4, 4)
print("Array:")
print(array_4x4)
print("\n")

# case 3 second diagonal better
print("Case 3 second diagonal better")
target = np.array([12, 9, 6, 3])
print(f"Searching for target: {target}")
print("\n")

indices = np.where(array_4x4 == target)
print("indices")
print(indices)
print("\n")

if len(indices[0]):
    ys = indices[0]
    xs = indices[1]
    values_by_idx = array_4x4[(ys, xs)]
    print("values_by_idx")
    print(values_by_idx)
else:
    print("No indices were found.")
    print("values_by_idx = []")

<font size="4">Phew! <br />
    This time np.where worked!                           <br /> 
    So what's the deal?                                  <br /><br />
    **np.where is an element-wise match based on the given condition.** <br />
    Numpy broadcasts the target to the array to be searched over. <br /><br />
    As a result np.where is sensitive to the position of the target values and the shape of the target array.<br />
    Notice that if we overlay the target array with the array to be searched over then all of the values in Case 3 are all in the correct position where as in Case 2 they are misaligned. <br /><br />
    To further see the element-wise comparison try using a target = np.array([12, 9, 6, 3, 15]) and see what happens.<br /><br />
    The bottom line is that **np.where is NOT a searching function** it's an element-wise matching function.
</font>

## Part 4.3: np.repeat & np.tile
<font size="4">Solve part 3 using np.repeat or np.tile. <br /><br />
    For the given integer 2D array multiply each row of the given masking array<br />
    by the given 2D array and then take the sum such that the shape of the given 2D array is preserved.<br /><br /></font>

<font size="4">Sometimes it's easier to think about broadcasting in terms of repeating elements and then multiplying.</font>
    
<pre>
Example:
given array:
            [[0 1 2]
             [3 4 5]
             [6 7 8]]

masking array:
            [[0 1 1]
             [1 1 0]]
        
repeat the given array by the number of masks
            [[[0 1 2]
              [3 4 5]
              [6 7 8]]

             [[0 1 2]
              [3 4 5]
              [6 7 8]]]

multiply the masks by the repeated array
            [[[0 1 2]            [[[0]         [[[0 0 0]
              [3 4 5]              [1]           [3 4 5]
              [6 7 8]]             [1]]          [6 7 8]]
                           *              =             
             [[0 1 2]             [[1]          [[0 1 2]
              [3 4 5]              [1]           [3 4 5]
              [6 7 8]]]            [0]]]         [0 0 0]]]  

take sum over first dimension:
            [[ 0  1  2]
             [ 6  8 10]
             [ 6  7  8]]

<font size="4" color="red">**task 4.3.1: Compute using numpy implementation. (4 points).**</font><br><br>

In [ ]:
def mask_multiply_by_repeat_np(array_2d: np.ndarray, mask_2d: np.ndarray):
    """
    Multiplies each row of the given masking array by the given 2D array
    and returns the sum such that the shape of the given 2D array is preserved.

    See above example for more information.

    Args:
        array_2d: A numpy array where N is the number of rows and M columns.
            shape (N, M)
        mask_2d: A numpy array where B is the number of masks of N columns.
            shape (B, N)

    Returns:
        final_sum: A numpy array representing the summed masked row of the given array.
            shape (N, M)
    """
    final_sum = None
    
    ###########################################################################
    #                           START OF YOUR CODE                            #
    ###########################################################################
    
    raise NotImplementedError
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    
    return final_sum

In [ ]:
# let's check your numpy implementation

# Test 1
test_mask_multiply_1(mask_multiply_by_repeat_np)

# Test 2
test_mask_multiply_2(mask_multiply_by_repeat_np)

# Test 3
test_mask_multiply_3(mask_multiply_by_repeat_np)

# Test 4
test_mask_multiply_4(mask_multiply_by_repeat_np)

# Test 5
test_mask_multiply_5(mask_multiply_by_repeat_np)

# Test 6
test_mask_multiply_6(mask_multiply_by_repeat_np)

# Test 7
test_mask_multiply_7(mask_multiply_by_repeat_np)

# Test 8
test_mask_multiply_8(mask_multiply_by_repeat_np)

<font size="4" color="red">**END**</font>